import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { TRPCReactProvider } from "@/trpc/react";
import Breadcrumbs from "./_components/breadcrumbs";

export const metadata: Metadata = {
	title: "Prompt Manager",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className={`${GeistSans.variable}`}>
			<body>
				<TRPCReactProvider>
					<Breadcrumbs />
					{children}
				</TRPCReactProvider>
			</body>
		</html>
	);
}
